// <auto-generated>Generated by scripts/gen-name-tables.py from Unicode 16.0.0 data and UTS #39 confusables 18.0.0. Don't edit by hand.</auto-generated>
// Contains data derived from the Unicode Character Database and UTS #39. Copyright (c) Unicode, Inc. Used under the
// Unicode License v3: https://www.unicode.org/license.txt
#nullable enable
using System.Collections.Frozen;

namespace TeamsWork.Ticketing.Mcp.Tools;

/// <summary>
/// Code points that display as plain Latin letters or digits, mapped to them in lower case: the compatibility forms NFKC
/// folds (full-width, mathematical, circled and squared letters, ligatures, Roman numerals) and the UTS #39 confusables
/// whose prototype is plain Latin (Greek and Cyrillic look-alikes, small capitals), so the name check needs no
/// globalisation data at run time.
/// </summary>
internal static class LookAlikes
{
    // Code point (hexadecimal) = the plain letters it looks like, separated by semicolons.
    private const string Data =
        "A1=i;A2=c;A5=y;AA=a;B2=2;B3=3;B9=1;BA=o;C6=ae;D0=d;D7=x;D8=o;" +
        "E6=ae;F8=o;FE=p;110=d;111=d;126=h;127=h;131=i;132=lj;133=ij;141=l;142=l;" +
        "14B=n;152=oe;153=oe;166=t;167=t;17F=f;180=b;182=b;183=b;184=b;189=d;18B=d;" +
        "18C=d;18D=g;191=f;192=f;196=l;197=l;199=k;19A=l;19D=n;19E=n;19F=o;1A5=p;" +
        "1A6=r;1A7=2;1AB=t;1AD=t;1AE=t;1B4=y;1B5=z;1B6=z;1B7=3;1BB=2;1BC=5;1BD=s;" +
        "1BF=p;1C0=l;1C1=ll;1C4=dz;1C5=dz;1C6=dz;1C7=lj;1C8=lj;1C9=lj;1CA=nj;1CB=nj;1CC=nj;" +
        "1E4=g;1E5=g;1F1=dz;1F2=dz;1F3=dz;21C=3;222=8;223=8;224=z;225=z;237=j;23C=c;" +
        "23E=t;244=u;246=e;247=e;248=j;249=j;24C=r;24D=r;24E=y;24F=y;251=a;253=b;" +
        "256=d;257=d;25F=j;260=g;261=g;262=g;263=y;266=h;268=i;269=i;26A=i;26B=l;" +
        "26D=l;26F=w;271=rn;272=n;273=n;274=n;275=o;27C=r;27D=r;280=r;282=s;284=f;" +
        "28B=u;28F=y;290=z;299=b;29C=h;29F=l;2A0=q;2A3=dz;2A6=ts;2A9=fn;2AA=ls;2AB=lz;" +
        "2B0=h;2B2=j;2B3=r;2B7=w;2B8=y;2E1=l;2E2=s;2E3=x;37F=j;391=a;392=b;395=e;" +
        "396=z;397=h;398=o;399=l;39A=k;39C=m;39D=n;39F=o;3A1=p;3A4=t;3A5=y;3A7=x;" +
        "3B1=a;3B3=y;3B7=n;3B8=o;3B9=i;3BD=v;3BF=o;3C1=p;3C3=o;3C5=u;3D1=o;3D2=y;" +
        "3DC=f;3E8=2;3EC=6;3ED=o;3F1=p;3F2=c;3F3=j;3F4=o;3F8=p;3F9=c;3FA=m;405=s;" +
        "406=l;408=j;410=a;411=b;412=b;415=e;417=3;41A=k;41C=m;41D=h;41E=o;420=p;" +
        "421=c;422=t;423=y;425=x;42B=bl;42C=b;42E=lo;430=a;431=6;433=r;435=e;43E=o;" +
        "440=p;441=c;443=y;445=x;448=w;455=s;456=i;458=j;45B=h;45F=u;461=w;462=b;" +
        "463=b;472=o;473=o;474=v;475=v;478=oy;479=oy;47D=w;48C=b;48D=b;493=r;498=3;" +
        "49A=k;49E=k;4A2=h;4AA=c;4AB=c;4AC=t;4AE=y;4AF=y;4B0=y;4B1=y;4B2=x;4BA=h;" +
        "4BB=h;4BD=e;4BF=e;4C0=l;4C7=h;4C9=h;4CD=m;4CF=l;4D4=ae;4D5=ae;4E0=3;4E8=o;" +
        "4E9=o;501=d;50C=g;51A=q;51B=q;51C=w;51D=w;545=3;54D=u;54F=s;555=o;560=rn;" +
        "561=w;563=q;566=q;570=h;572=n;575=j;578=n;57C=n;57D=u;581=g;582=i;584=f;" +
        "585=o;5C0=l;5D5=l;5D8=v;5DF=l;5E1=o;5F0=ll;627=l;629=o;647=o;661=l;665=o;" +
        "667=v;673=l;6BE=o;6C1=o;6C3=o;6D5=o;6F1=l;6F5=o;6F7=v;6FF=o;7C0=o;7CA=l;" +
        "7CB=o;7CC=y;7D3=f;7D5=b;7E0=t;840=o;964=l;965=ll;966=o;969=3;9E6=o;9EA=8;" +
        "9ED=9;A66=o;A67=9;A6A=8;AE6=o;AE9=3;B03=8;B20=o;B66=o;B68=9;BE6=o;C02=o;" +
        "C66=o;C82=o;CE6=o;D02=o;D1F=s;D20=o;D66=o;D6D=9;D82=o;E50=o;ED0=o;1004=c;" +
        "101D=o;1040=o;104A=l;104B=ll;105A=c;10B9=h;10BD=s;10C7=2;10CD=z;10E7=y;10FD=s;10FF=o;" +
        "110B=o;1147=oo;11BC=o;11EE=oo;1200=u;12D0=o;1340=o;13A0=d;13A1=r;13A2=t;13A4=o;13A5=i;" +
        "13A9=y;13AA=a;13AB=j;13AC=e;13B3=w;13B7=m;13BB=h;13BD=y;13BE=o;13BF=t;13C0=g;13C2=h;" +
        "13C3=z;13CC=u;13CE=4;13CF=b;13D2=r;13D4=w;13D5=s;13D9=v;13DA=s;13DE=l;13DF=c;13E2=p;" +
        "13E6=k;13E7=d;13EB=o;13EE=6;13F2=h;13F3=g;13F4=b;142F=v;144C=u;146D=p;146F=d;1472=b;" +
        "1473=b;148D=j;14AA=l;14BF=2;1541=x;157C=h;157D=x;1587=r;15AF=b;15B4=f;15C5=a;15DE=d;" +
        "15EA=d;15F0=m;15F7=b;1616=2;166D=x;166E=x;16B7=x;16C1=l;16C5=l;16D0=l;16D5=k;16D6=m;" +
        "1702=3;172A=7;1763=x;17E0=o;1A45=o;1A80=o;1A90=o;1BEA=o;1BEC=x;1C82=o;1C83=c;1C84=7;" +
        "1C95=3;1CB7=2;1CBD=s;1CBF=o;1CF5=x;1D00=a;1D04=c;1D05=d;1D07=e;1D0A=j;1D0B=k;1D0D=m;" +
        "1D0F=o;1D11=o;1D18=p;1D1B=t;1D1C=u;1D20=v;1D21=w;1D22=z;1D26=r;1D2C=a;1D2E=b;1D30=d;" +
        "1D31=e;1D33=g;1D34=h;1D35=i;1D36=j;1D37=k;1D38=l;1D39=m;1D3A=n;1D3C=o;1D3E=p;1D3F=r;" +
        "1D40=t;1D41=u;1D42=w;1D43=a;1D47=b;1D48=d;1D49=e;1D4D=g;1D4F=k;1D50=m;1D52=o;1D56=p;" +
        "1D57=t;1D58=u;1D5B=v;1D62=i;1D63=r;1D64=u;1D65=v;1D6B=ue;1D6E=f;1D6F=rn;1D70=n;1D72=r;" +
        "1D74=s;1D75=t;1D76=z;1D7B=i;1D7C=i;1D7D=p;1D7E=u;1D83=g;1D8C=y;1D9C=c;1DA0=f;1DBB=z;" +
        "1E9B=s;1E9D=f;1EFA=ll;1EFF=y;2016=ll;2070=0;2071=i;2074=4;2075=5;2076=6;2077=7;2078=8;" +
        "2079=9;207F=n;2080=0;2081=1;2082=2;2083=3;2084=4;2085=5;2086=6;2087=7;2088=8;2089=9;" +
        "2090=a;2091=e;2092=o;2093=x;2095=h;2096=k;2097=l;2098=m;2099=n;209A=p;209B=s;209C=t;" +
        "20A1=c;20A5=rn;20A8=rs;20A9=w;20AB=d;20AD=k;20AE=t;20B6=lt;2102=c;210A=g;210B=h;210C=h;" +
        "210D=h;210E=h;210F=h;2110=l;2111=l;2112=l;2113=l;2115=n;2116=no;2119=p;211A=q;211B=r;" +
        "211C=r;211D=r;2120=sm;2121=tel;2122=tm;2124=z;2128=z;212B=a;212C=b;212D=c;212E=e;212F=e;" +
        "2130=e;2131=f;2133=m;2134=o;2139=i;213B=fax;213D=y;2145=d;2146=d;2147=e;2148=i;2149=j;" +
        "2160=l;2161=ll;2162=lll;2163=lv;2164=v;2165=vl;2166=vll;2167=vlll;2168=lx;2169=x;216A=xl;216B=xll;" +
        "216C=l;216D=c;216E=d;216F=m;2170=i;2171=ii;2172=iii;2173=iv;2174=v;2175=vi;2176=vii;2177=viii;" +
        "2178=ix;2179=x;217A=xi;217B=xii;217C=l;217D=c;217E=d;217F=rn;21BF=l;2205=o;221E=oo;2223=l;" +
        "2225=ll;2228=v;222A=u;2296=o;229D=o;22A4=t;22C1=v;22C3=u;22FF=e;2300=o;2361=t;2365=o;" +
        "236C=o;2373=i;2374=p;2376=a;2378=i;237A=a;23FD=l;2460=1;2461=2;2462=3;2463=4;2464=5;" +
        "2465=6;2466=7;2467=8;2468=9;2469=10;246A=11;246B=12;246C=13;246D=14;246E=15;246F=16;2470=17;" +
        "2471=18;2472=19;2473=20;24B6=a;24B7=b;24B8=c;24B9=d;24BA=e;24BB=f;24BC=g;24BD=h;24BE=i;" +
        "24BF=j;24C0=k;24C1=l;24C2=m;24C3=n;24C4=o;24C5=p;24C6=q;24C7=r;24C8=s;24C9=t;24CA=u;" +
        "24CB=v;24CC=w;24CD=x;24CE=y;24CF=z;24D0=a;24D1=b;24D2=c;24D3=d;24D4=e;24D5=f;24D6=g;" +
        "24D7=h;24D8=i;24D9=j;24DA=k;24DB=l;24DC=m;24DD=n;24DE=o;24DF=p;24E0=q;24E1=r;24E2=s;" +
        "24E3=t;24E4=u;24E5=v;24E6=w;24E7=x;24E8=y;24E9=z;24EA=0;2502=l;2503=l;2573=x;27D9=t;" +
        "292B=x;292C=x;29E2=w;2A2F=x;2A30=x;2C67=h;2C69=k;2C6B=z;2C6C=z;2C7C=j;2C7D=v;2C82=b;" +
        "2C85=r;2C8C=z;2C8D=z;2C8E=h;2C90=o;2C91=o;2C92=l;2C93=i;2C94=k;2C98=m;2C9A=n;2C9C=3;" +
        "2C9E=o;2C9F=o;2CA2=p;2CA3=p;2CA4=c;2CA5=c;2CA6=t;2CA8=y;2CA9=y;2CAC=x;2CBD=w;2CC4=3;" +
        "2CCA=9;2CCB=9;2CCC=3;2CCE=p;2CCF=p;2CD0=l;2CD2=6;2CD3=6;2CDC=6;2D2D=z;2D31=o;2D38=v;" +
        "2D39=e;2D41=o;2D4A=l;2D4F=l;2D54=o;2D55=q;2D5D=x;3007=o;3112=t;311A=y;3147=o;3180=oo;" +
        "3250=pte;3251=21;3252=22;3253=23;3254=24;3255=25;3256=26;3257=27;3258=28;3259=29;325A=30;325B=31;" +
        "325C=32;325D=33;325E=34;325F=35;32B1=36;32B2=37;32B3=38;32B4=39;32B5=40;32B6=41;32B7=42;32B8=43;" +
        "32B9=44;32BA=45;32BB=46;32BC=47;32BD=48;32BE=49;32BF=50;32CC=hg;32CD=erg;32CE=ev;32CF=ltd;3371=hpa;" +
        "3372=da;3373=au;3374=bar;3375=ov;3376=pc;3377=drn;3378=dm2;3379=dm3;337A=lu;3380=pa;3381=na;3383=rna;" +
        "3384=ka;3385=kb;3386=mb;3387=gb;3388=cal;3389=kcal;338A=pf;338B=nf;338E=rng;338F=kg;3390=hz;3391=khz;" +
        "3392=mhz;3393=ghz;3394=thz;3396=rnl;3397=dl;3398=kl;3399=frn;339A=nrn;339C=rnrn;339D=crn;339E=krn;339F=mm2;" +
        "33A0=cm2;33A1=m2;33A2=km2;33A3=mm3;33A4=cm3;33A5=m3;33A6=km3;33A9=pa;33AA=kpa;33AB=mpa;33AC=gpa;33AD=rad;" +
        "33B0=ps;33B1=ns;33B3=rns;33B4=pv;33B5=nv;33B7=rnv;33B8=kv;33B9=mv;33BA=pw;33BB=nw;33BD=rnw;33BE=kw;" +
        "33BF=mw;33C3=bq;33C4=cc;33C5=cd;33C8=db;33C9=gy;33CA=ha;33CB=hp;33CC=in;33CD=kk;33CE=km;33CF=kt;" +
        "33D0=lrn;33D1=ln;33D2=log;33D3=lx;33D4=rnb;33D5=rnil;33D6=rnol;33D7=ph;33D9=ppm;33DA=pr;33DB=sr;33DC=sv;" +
        "33DD=wb;33FF=gal;4E05=t;4E2B=y;A4D0=b;A4D1=p;A4D2=d;A4D3=d;A4D4=t;A4D6=g;A4D7=k;A4D9=j;" +
        "A4DA=c;A4DC=z;A4DD=f;A4DF=m;A4E0=n;A4E1=l;A4E2=s;A4E3=r;A4E6=v;A4E7=h;A4EA=w;A4EB=x;" +
        "A4EC=y;A4EE=a;A4F0=e;A4F2=l;A4F3=o;A4F4=u;A50B=t;A516=lll;A543=6;A557=b;A56F=l;A576=s;" +
        "A589=8;A5CB=e;A644=2;A647=i;A68C=t;A695=h;A698=oo;A699=oo;A6A2=o;A6B2=y;A6C9=z;A6DF=v;" +
        "A6EF=2;A728=t3;A730=f;A731=s;A732=aa;A733=aa;A734=ao;A735=ao;A736=au;A737=au;A738=av;A739=av;" +
        "A73A=av;A73B=av;A73C=ay;A73D=ay;A740=k;A74A=o;A74B=o;A74E=oo;A74F=oo;A75A=2;A761=w;A76A=3;" +
        "A76E=9;A76F=9;A777=tf;A781=l;A798=f;A799=f;A79F=u;A7AB=3;A7AE=l;A7AF=q;A7B2=j;A7B3=x;" +
        "A7B4=b;A7C5=s;A7F2=c;A7F3=f;A7F4=q;A7FA=w;A7FE=l;A830=l;A8CE=l;A8CF=ll;A8F6=3;AA5D=l;" +
        "AB32=e;AB35=f;AB3D=o;AB3E=o;AB43=co;AB44=co;AB47=r;AB48=r;AB4E=u;AB51=rn;AB52=u;AB5A=y;" +
        "AB63=uo;AB64=a;AB74=o;AB75=i;AB81=r;AB83=w;AB8E=o;AB93=z;AB9C=u;AB9E=4;ABA4=w;ABA9=v;" +
        "ABAA=s;ABAF=c;ABBB=o;ABBE=6;FB00=ff;FB01=fi;FB02=fl;FB03=ffi;FB04=ffl;FB05=ft;FB06=st;FBA4=o;" +
        "FBA5=o;FBA6=o;FBA7=o;FBA8=o;FBA9=o;FBAA=o;FBAB=o;FBAC=o;FBAD=o;FCD9=o;FD3C=l;FD3D=l;" +
        "FE31=l;FE81=l;FE82=l;FE87=l;FE88=l;FE8D=l;FE8E=l;FE93=o;FE94=o;FEE9=o;FEEA=o;FEEB=o;" +
        "FEEC=o;FF10=o;FF11=l;FF12=2;FF13=3;FF14=4;FF15=5;FF16=6;FF17=7;FF18=8;FF19=9;FF21=a;" +
        "FF22=b;FF23=c;FF24=d;FF25=e;FF26=f;FF27=g;FF28=h;FF29=l;FF2A=j;FF2B=k;FF2C=l;FF2D=m;" +
        "FF2E=n;FF2F=o;FF30=p;FF31=q;FF32=r;FF33=s;FF34=t;FF35=u;FF36=v;FF37=w;FF38=x;FF39=y;" +
        "FF3A=z;FF41=a;FF42=b;FF43=c;FF44=d;FF45=e;FF46=f;FF47=g;FF48=h;FF49=i;FF4A=j;FF4B=k;" +
        "FF4C=l;FF4D=rn;FF4E=n;FF4F=o;FF50=p;FF51=q;FF52=r;FF53=s;FF54=t;FF55=u;FF56=v;FF57=w;" +
        "FF58=x;FF59=y;FF5A=z;FF5C=l;FFB7=o;FFE0=c;FFE5=y;FFE6=w;FFE8=l;1017E=f;1018B=d;1018E=n;" +
        "10196=x;10197=v;10198=lls;10199=ll;10282=b;10286=e;10287=f;1028A=l;10290=x;10292=o;10295=p;10296=s;" +
        "10297=t;102A0=a;102A1=b;102A2=c;102A5=f;102AB=o;102B0=m;102B1=t;102B2=y;102B4=x;102CF=h;102F5=z;" +
        "10301=b;10302=c;10309=l;1030F=o;10311=m;10315=t;10317=x;1031A=8;1031C=b;10320=l;10322=x;10404=o;" +
        "10415=c;1041B=l;10420=s;1042C=o;1043D=c;10448=s;104B4=r;104C2=o;104CE=u;104D2=7;104EA=o;104F6=u;" +
        "10507=z;1050E=l;10513=n;10516=o;10518=k;1051B=c;1051D=v;1051E=o;10525=f;10526=l;10527=x;107A5=q;" +
        "10926=l;1092C=o;10C13=x;10C17=o;10C1F=v;10C20=y;10C21=m;10C3E=l;10C82=x;10CA5=l;10CC2=x;10CFA=l;" +
        "10CFC=x;10D07=o;11047=l;11048=ll;110C0=l;110C1=ll;11124=o;11141=l;11142=ll;111C5=l;111C6=ll;11302=o;" +
        "113D4=l;113D5=ll;11445=8;1144B=l;1144C=ll;114C5=w;114D0=o;115C5=l;11641=l;11642=ll;11700=rn;11706=v;" +
        "1170A=w;1170E=w;1170F=w;118A0=v;118A2=f;118A3=l;118A4=y;118A6=e;118A9=z;118AC=9;118AE=e;118AF=4;" +
        "118B2=l;118B5=o;118B8=u;118BB=5;118BC=t;118C0=v;118C1=s;118C2=f;118C3=i;118C4=y;118C6=7;118C8=o;" +
        "118CA=3;118CC=9;118D5=6;118D6=9;118D7=o;118D8=u;118DC=y;118E0=o;118E3=rn;118E5=z;118E6=w;118E9=c;" +
        "118EC=x;118EF=w;118F2=c;11ABC=z;11ABE=n;11C41=l;11C42=ll;1699B=o;169C1=9;169FE=8;16A19=r;16AD6=s;" +
        "16AE4=l;16AE9=o;16D63=l;16E80=o;16E82=4;16E8A=7;16F08=v;16F0A=t;16F16=l;16F28=l;16F35=r;16F3A=s;" +
        "16F3B=3;16F40=a;16F42=u;16F43=y;1CCD6=a;1CCD7=b;1CCD8=c;1CCD9=d;1CCDA=e;1CCDB=f;1CCDC=g;1CCDD=h;" +
        "1CCDE=l;1CCDF=j;1CCE0=k;1CCE1=l;1CCE2=m;1CCE3=n;1CCE4=o;1CCE5=p;1CCE6=q;1CCE7=r;1CCE8=s;1CCE9=t;" +
        "1CCEA=u;1CCEB=v;1CCEC=w;1CCED=x;1CCEE=y;1CCEF=z;1CCF0=o;1CCF1=l;1CCF2=2;1CCF3=3;1CCF4=4;1CCF5=5;" +
        "1CCF6=6;1CCF7=7;1CCF8=8;1CCF9=9;1D100=l;1D134=c;1D206=3;1D207=b;1D20C=w;1D20D=v;1D212=7;1D213=f;" +
        "1D216=r;1D21A=o;1D22A=l;1D373=t;1D377=l;1D400=a;1D401=b;1D402=c;1D403=d;1D404=e;1D405=f;1D406=g;" +
        "1D407=h;1D408=l;1D409=j;1D40A=k;1D40B=l;1D40C=m;1D40D=n;1D40E=o;1D40F=p;1D410=q;1D411=r;1D412=s;" +
        "1D413=t;1D414=u;1D415=v;1D416=w;1D417=x;1D418=y;1D419=z;1D41A=a;1D41B=b;1D41C=c;1D41D=d;1D41E=e;" +
        "1D41F=f;1D420=g;1D421=h;1D422=i;1D423=j;1D424=k;1D425=l;1D426=rn;1D427=n;1D428=o;1D429=p;1D42A=q;" +
        "1D42B=r;1D42C=s;1D42D=t;1D42E=u;1D42F=v;1D430=w;1D431=x;1D432=y;1D433=z;1D434=a;1D435=b;1D436=c;" +
        "1D437=d;1D438=e;1D439=f;1D43A=g;1D43B=h;1D43C=l;1D43D=j;1D43E=k;1D43F=l;1D440=m;1D441=n;1D442=o;" +
        "1D443=p;1D444=q;1D445=r;1D446=s;1D447=t;1D448=u;1D449=v;1D44A=w;1D44B=x;1D44C=y;1D44D=z;1D44E=a;" +
        "1D44F=b;1D450=c;1D451=d;1D452=e;1D453=f;1D454=g;1D456=i;1D457=j;1D458=k;1D459=l;1D45A=rn;1D45B=n;" +
        "1D45C=o;1D45D=p;1D45E=q;1D45F=r;1D460=s;1D461=t;1D462=u;1D463=v;1D464=w;1D465=x;1D466=y;1D467=z;" +
        "1D468=a;1D469=b;1D46A=c;1D46B=d;1D46C=e;1D46D=f;1D46E=g;1D46F=h;1D470=l;1D471=j;1D472=k;1D473=l;" +
        "1D474=m;1D475=n;1D476=o;1D477=p;1D478=q;1D479=r;1D47A=s;1D47B=t;1D47C=u;1D47D=v;1D47E=w;1D47F=x;" +
        "1D480=y;1D481=z;1D482=a;1D483=b;1D484=c;1D485=d;1D486=e;1D487=f;1D488=g;1D489=h;1D48A=i;1D48B=j;" +
        "1D48C=k;1D48D=l;1D48E=rn;1D48F=n;1D490=o;1D491=p;1D492=q;1D493=r;1D494=s;1D495=t;1D496=u;1D497=v;" +
        "1D498=w;1D499=x;1D49A=y;1D49B=z;1D49C=a;1D49E=c;1D49F=d;1D4A2=g;1D4A5=j;1D4A6=k;1D4A9=n;1D4AA=o;" +
        "1D4AB=p;1D4AC=q;1D4AE=s;1D4AF=t;1D4B0=u;1D4B1=v;1D4B2=w;1D4B3=x;1D4B4=y;1D4B5=z;1D4B6=a;1D4B7=b;" +
        "1D4B8=c;1D4B9=d;1D4BB=f;1D4BD=h;1D4BE=i;1D4BF=j;1D4C0=k;1D4C1=l;1D4C2=rn;1D4C3=n;1D4C5=p;1D4C6=q;" +
        "1D4C7=r;1D4C8=s;1D4C9=t;1D4CA=u;1D4CB=v;1D4CC=w;1D4CD=x;1D4CE=y;1D4CF=z;1D4D0=a;1D4D1=b;1D4D2=c;" +
        "1D4D3=d;1D4D4=e;1D4D5=f;1D4D6=g;1D4D7=h;1D4D8=l;1D4D9=j;1D4DA=k;1D4DB=l;1D4DC=m;1D4DD=n;1D4DE=o;" +
        "1D4DF=p;1D4E0=q;1D4E1=r;1D4E2=s;1D4E3=t;1D4E4=u;1D4E5=v;1D4E6=w;1D4E7=x;1D4E8=y;1D4E9=z;1D4EA=a;" +
        "1D4EB=b;1D4EC=c;1D4ED=d;1D4EE=e;1D4EF=f;1D4F0=g;1D4F1=h;1D4F2=i;1D4F3=j;1D4F4=k;1D4F5=l;1D4F6=rn;" +
        "1D4F7=n;1D4F8=o;1D4F9=p;1D4FA=q;1D4FB=r;1D4FC=s;1D4FD=t;1D4FE=u;1D4FF=v;1D500=w;1D501=x;1D502=y;" +
        "1D503=z;1D504=a;1D505=b;1D507=d;1D508=e;1D509=f;1D50A=g;1D50D=j;1D50E=k;1D50F=l;1D510=m;1D511=n;" +
        "1D512=o;1D513=p;1D514=q;1D516=s;1D517=t;1D518=u;1D519=v;1D51A=w;1D51B=x;1D51C=y;1D51E=a;1D51F=b;" +
        "1D520=c;1D521=d;1D522=e;1D523=f;1D524=g;1D525=h;1D526=i;1D527=j;1D528=k;1D529=l;1D52A=rn;1D52B=n;" +
        "1D52C=o;1D52D=p;1D52E=q;1D52F=r;1D530=s;1D531=t;1D532=u;1D533=v;1D534=w;1D535=x;1D536=y;1D537=z;" +
        "1D538=a;1D539=b;1D53B=d;1D53C=e;1D53D=f;1D53E=g;1D540=l;1D541=j;1D542=k;1D543=l;1D544=m;1D546=o;" +
        "1D54A=s;1D54B=t;1D54C=u;1D54D=v;1D54E=w;1D54F=x;1D550=y;1D552=a;1D553=b;1D554=c;1D555=d;1D556=e;" +
        "1D557=f;1D558=g;1D559=h;1D55A=i;1D55B=j;1D55C=k;1D55D=l;1D55E=rn;1D55F=n;1D560=o;1D561=p;1D562=q;" +
        "1D563=r;1D564=s;1D565=t;1D566=u;1D567=v;1D568=w;1D569=x;1D56A=y;1D56B=z;1D56C=a;1D56D=b;1D56E=c;" +
        "1D56F=d;1D570=e;1D571=f;1D572=g;1D573=h;1D574=l;1D575=j;1D576=k;1D577=l;1D578=m;1D579=n;1D57A=o;" +
        "1D57B=p;1D57C=q;1D57D=r;1D57E=s;1D57F=t;1D580=u;1D581=v;1D582=w;1D583=x;1D584=y;1D585=z;1D586=a;" +
        "1D587=b;1D588=c;1D589=d;1D58A=e;1D58B=f;1D58C=g;1D58D=h;1D58E=i;1D58F=j;1D590=k;1D591=l;1D592=rn;" +
        "1D593=n;1D594=o;1D595=p;1D596=q;1D597=r;1D598=s;1D599=t;1D59A=u;1D59B=v;1D59C=w;1D59D=x;1D59E=y;" +
        "1D59F=z;1D5A0=a;1D5A1=b;1D5A2=c;1D5A3=d;1D5A4=e;1D5A5=f;1D5A6=g;1D5A7=h;1D5A8=l;1D5A9=j;1D5AA=k;" +
        "1D5AB=l;1D5AC=m;1D5AD=n;1D5AE=o;1D5AF=p;1D5B0=q;1D5B1=r;1D5B2=s;1D5B3=t;1D5B4=u;1D5B5=v;1D5B6=w;" +
        "1D5B7=x;1D5B8=y;1D5B9=z;1D5BA=a;1D5BB=b;1D5BC=c;1D5BD=d;1D5BE=e;1D5BF=f;1D5C0=g;1D5C1=h;1D5C2=i;" +
        "1D5C3=j;1D5C4=k;1D5C5=l;1D5C6=rn;1D5C7=n;1D5C8=o;1D5C9=p;1D5CA=q;1D5CB=r;1D5CC=s;1D5CD=t;1D5CE=u;" +
        "1D5CF=v;1D5D0=w;1D5D1=x;1D5D2=y;1D5D3=z;1D5D4=a;1D5D5=b;1D5D6=c;1D5D7=d;1D5D8=e;1D5D9=f;1D5DA=g;" +
        "1D5DB=h;1D5DC=l;1D5DD=j;1D5DE=k;1D5DF=l;1D5E0=m;1D5E1=n;1D5E2=o;1D5E3=p;1D5E4=q;1D5E5=r;1D5E6=s;" +
        "1D5E7=t;1D5E8=u;1D5E9=v;1D5EA=w;1D5EB=x;1D5EC=y;1D5ED=z;1D5EE=a;1D5EF=b;1D5F0=c;1D5F1=d;1D5F2=e;" +
        "1D5F3=f;1D5F4=g;1D5F5=h;1D5F6=i;1D5F7=j;1D5F8=k;1D5F9=l;1D5FA=rn;1D5FB=n;1D5FC=o;1D5FD=p;1D5FE=q;" +
        "1D5FF=r;1D600=s;1D601=t;1D602=u;1D603=v;1D604=w;1D605=x;1D606=y;1D607=z;1D608=a;1D609=b;1D60A=c;" +
        "1D60B=d;1D60C=e;1D60D=f;1D60E=g;1D60F=h;1D610=l;1D611=j;1D612=k;1D613=l;1D614=m;1D615=n;1D616=o;" +
        "1D617=p;1D618=q;1D619=r;1D61A=s;1D61B=t;1D61C=u;1D61D=v;1D61E=w;1D61F=x;1D620=y;1D621=z;1D622=a;" +
        "1D623=b;1D624=c;1D625=d;1D626=e;1D627=f;1D628=g;1D629=h;1D62A=i;1D62B=j;1D62C=k;1D62D=l;1D62E=rn;" +
        "1D62F=n;1D630=o;1D631=p;1D632=q;1D633=r;1D634=s;1D635=t;1D636=u;1D637=v;1D638=w;1D639=x;1D63A=y;" +
        "1D63B=z;1D63C=a;1D63D=b;1D63E=c;1D63F=d;1D640=e;1D641=f;1D642=g;1D643=h;1D644=l;1D645=j;1D646=k;" +
        "1D647=l;1D648=m;1D649=n;1D64A=o;1D64B=p;1D64C=q;1D64D=r;1D64E=s;1D64F=t;1D650=u;1D651=v;1D652=w;" +
        "1D653=x;1D654=y;1D655=z;1D656=a;1D657=b;1D658=c;1D659=d;1D65A=e;1D65B=f;1D65C=g;1D65D=h;1D65E=i;" +
        "1D65F=j;1D660=k;1D661=l;1D662=rn;1D663=n;1D664=o;1D665=p;1D666=q;1D667=r;1D668=s;1D669=t;1D66A=u;" +
        "1D66B=v;1D66C=w;1D66D=x;1D66E=y;1D66F=z;1D670=a;1D671=b;1D672=c;1D673=d;1D674=e;1D675=f;1D676=g;" +
        "1D677=h;1D678=l;1D679=j;1D67A=k;1D67B=l;1D67C=m;1D67D=n;1D67E=o;1D67F=p;1D680=q;1D681=r;1D682=s;" +
        "1D683=t;1D684=u;1D685=v;1D686=w;1D687=x;1D688=y;1D689=z;1D68A=a;1D68B=b;1D68C=c;1D68D=d;1D68E=e;" +
        "1D68F=f;1D690=g;1D691=h;1D692=i;1D693=j;1D694=k;1D695=l;1D696=rn;1D697=n;1D698=o;1D699=p;1D69A=q;" +
        "1D69B=r;1D69C=s;1D69D=t;1D69E=u;1D69F=v;1D6A0=w;1D6A1=x;1D6A2=y;1D6A3=z;1D6A4=i;1D6A5=j;1D6A8=a;" +
        "1D6A9=b;1D6AC=e;1D6AD=z;1D6AE=h;1D6AF=o;1D6B0=l;1D6B1=k;1D6B3=m;1D6B4=n;1D6B6=o;1D6B8=p;1D6B9=o;" +
        "1D6BB=t;1D6BC=y;1D6BE=x;1D6C2=a;1D6C4=y;1D6C8=n;1D6C9=o;1D6CA=i;1D6CE=v;1D6D0=o;1D6D2=p;1D6D4=o;" +
        "1D6D6=u;1D6DD=o;1D6E0=p;1D6E2=a;1D6E3=b;1D6E6=e;1D6E7=z;1D6E8=h;1D6E9=o;1D6EA=l;1D6EB=k;1D6ED=m;" +
        "1D6EE=n;1D6F0=o;1D6F2=p;1D6F3=o;1D6F5=t;1D6F6=y;1D6F8=x;1D6FC=a;1D6FE=y;1D702=n;1D703=o;1D704=i;" +
        "1D708=v;1D70A=o;1D70C=p;1D70E=o;1D710=u;1D717=o;1D71A=p;1D71C=a;1D71D=b;1D720=e;1D721=z;1D722=h;" +
        "1D723=o;1D724=l;1D725=k;1D727=m;1D728=n;1D72A=o;1D72C=p;1D72D=o;1D72F=t;1D730=y;1D732=x;1D736=a;" +
        "1D738=y;1D73C=n;1D73D=o;1D73E=i;1D742=v;1D744=o;1D746=p;1D748=o;1D74A=u;1D751=o;1D754=p;1D756=a;" +
        "1D757=b;1D75A=e;1D75B=z;1D75C=h;1D75D=o;1D75E=l;1D75F=k;1D761=m;1D762=n;1D764=o;1D766=p;1D767=o;" +
        "1D769=t;1D76A=y;1D76C=x;1D770=a;1D772=y;1D776=n;1D777=o;1D778=i;1D77C=v;1D77E=o;1D780=p;1D782=o;" +
        "1D784=u;1D78B=o;1D78E=p;1D790=a;1D791=b;1D794=e;1D795=z;1D796=h;1D797=o;1D798=l;1D799=k;1D79B=m;" +
        "1D79C=n;1D79E=o;1D7A0=p;1D7A1=o;1D7A3=t;1D7A4=y;1D7A6=x;1D7AA=a;1D7AC=y;1D7B0=n;1D7B1=o;1D7B2=i;" +
        "1D7B6=v;1D7B8=o;1D7BA=p;1D7BC=o;1D7BE=u;1D7C5=o;1D7C8=p;1D7CA=f;1D7CE=o;1D7CF=l;1D7D0=2;1D7D1=3;" +
        "1D7D2=4;1D7D3=5;1D7D4=6;1D7D5=7;1D7D6=8;1D7D7=9;1D7D8=o;1D7D9=l;1D7DA=2;1D7DB=3;1D7DC=4;1D7DD=5;" +
        "1D7DE=6;1D7DF=7;1D7E0=8;1D7E1=9;1D7E2=o;1D7E3=l;1D7E4=2;1D7E5=3;1D7E6=4;1D7E7=5;1D7E8=6;1D7E9=7;" +
        "1D7EA=8;1D7EB=9;1D7EC=o;1D7ED=l;1D7EE=2;1D7EF=3;1D7F0=4;1D7F1=5;1D7F2=6;1D7F3=7;1D7F4=8;1D7F5=9;" +
        "1D7F6=o;1D7F7=l;1D7F8=2;1D7F9=3;1D7FA=4;1D7FB=5;1D7FC=6;1D7FD=7;1D7FE=8;1D7FF=9;1E140=o;1E141=l;" +
        "1E145=v;1E2F0=o;1E2F2=9;1E8C7=l;1E8CB=8;1ED01=l;1EE00=l;1EE24=o;1EE64=ol;1EE80=l;1EE84=o;1F12B=c;" +
        "1F12C=r;1F12D=cd;1F12E=wz;1F130=a;1F131=b;1F132=c;1F133=d;1F134=e;1F135=f;1F136=g;1F137=h;1F138=i;" +
        "1F139=j;1F13A=k;1F13B=l;1F13C=m;1F13D=n;1F13E=o;1F13F=p;1F140=q;1F141=r;1F142=s;1F143=t;1F144=u;" +
        "1F145=v;1F146=w;1F147=x;1F148=y;1F149=z;1F14A=hv;1F14B=mv;1F14C=sd;1F14D=ss;1F14E=ppv;1F14F=wc;1F16A=mc;" +
        "1F16B=md;1F16C=mr;1F16D=cc;1F16E=c;1F190=dj;1F700=qe;1F707=ar;1F708=v;1F714=o;1F74C=c;1F75C=sss;1F768=t;" +
        "1F76B=mb;1F76C=vb;1FBF0=o;1FBF1=l;1FBF2=2;1FBF3=3;1FBF4=4;1FBF5=5;1FBF6=6;1FBF7=7;1FBF8=8;1FBF9=9;";

    private static readonly FrozenDictionary<int, string> Map = Data
        .Split(';', StringSplitOptions.RemoveEmptyEntries)
        .Select(e => e.Split('='))
        .ToFrozenDictionary(e => int.Parse(e[0], System.Globalization.NumberStyles.HexNumber, System.Globalization.CultureInfo.InvariantCulture), e => e[1]);

    /// <summary>The plain lower-case letters <paramref name="c"/> looks like, or null when it isn't a look-alike.</summary>
    public static string? Of(int c) => Map.GetValueOrDefault(c);
}
